<div class="card text-start mb-3 container" style="width: 38rem; background: #f8f9fb">
  <div class="card-body">
    <h1 class="card-title">Произошла ошибка</h1>
    <?php if ($details === true): ?>
      <p>Приложение не работает по следующим причинам:</p>
      <?php if (isset($type)): ?>
        <div><strong>Тип: </strong><?= $type ?></dev>
      <?php endif ?>
      <div><strong>Код: </strong><?= $code ?></div>
      <div><strong>Сообщение: </strong><?= htmlspecialchars($message) ?></div>
    <?php else: ?>
      <div><strong>Сообщение: </strong><?= htmlspecialchars($message) ?></div>
    <?php endif ?>
  </div>
</div>
