<head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
</head>
<body>
  <div class="card" style="height: 100vh">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand text-body-light" href="/">Анализатор страниц</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link text-body-light" aria-current="page" href="/">Главная</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-body-light" href="/urls">Сайты</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="card-body sticky-xl-top">
      <div class="card text-start mb-3 container" style="width: 38rem; background: #f8f9fb">
        <div class="card-body">
          <h1 class="card-title">Произошла ошибка</h1>
          <p class="card-text"><?= $exceptionFragment ?></p>
        </div>
      </div>
    </div>

    <div class="card-footer sticky-bottom text-center text-body-secondary">
      <a href="https://ru.hexlet.io/pages/about">Hexlet</a>
    </div>
  </div>
</body>