<div class="text-start mb-2 container" style="width: 100vw">
  <h1>Сайт: <?= htmlspecialchars($name ?: '', ENT_QUOTES) ?></h1>
  <table class="table table-bordered border-primary" data-test="url">
    <tr>
      <th>ID</th>
      <td><?= htmlspecialchars($id ?: '', ENT_QUOTES) ?></td>
    </tr>
    <tr>
      <th>Имя</th>
      <td><?= htmlspecialchars($name ?: '', ENT_QUOTES) ?></td>
    </tr>
    <tr>
      <th>Дата создания</th>
      <td><?= htmlspecialchars($timestamp ?: '', ENT_QUOTES) ?></td>
    </tr>
  </table>
</div>

<div class="text-start mb-2 container" style="width: 100vw; margin-top: 4rem">
  <h1>Проверки</h1>
  <form action="/urls/<?= htmlspecialchars($id ?: '', ENT_QUOTES) ?>/checks" method='post'>
    <input type='submit' class="btn btn-primary btn-sm" value='Запустить проверку'>
  </form>
  <table class="table table-bordered border-primary" data-test="checks">
    <thead>
      <tr>
        <th>ID</th>
        <th>Код ответа</th>
        <th>h1</th>
        <th>title</th>
        <th>Description</th>
        <th>Дата создания</th>
      </tr>
    </head>
    <tbody>
      <?php foreach ($checks as $check): ?>
        <tr>
          <td><?= htmlspecialchars($check['id'] ?: '', ENT_QUOTES) ?></td>
          <td><?= htmlspecialchars($check['status'] ?: '', ENT_QUOTES) ?></td>
          <td><?= htmlspecialchars($check['h1'] ?: '', ENT_QUOTES) ?></td>
          <td><?= htmlspecialchars($check['title'] ?: '', ENT_QUOTES) ?></td>
          <td><?= htmlspecialchars($check['description'] ?: '', ENT_QUOTES) ?></td>
          <td><?= htmlspecialchars($check['timestamp'] ?: '', ENT_QUOTES) ?></td>
        </tr>
      <?php endforeach ?>
    </tbody>
  </table>
</div>
