<head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
</head>
<body>
  <div class="card" style="height: 100vh">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand text-body-light" href="/">Анализатор страниц</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link text-body-light" aria-current="page" href="/">Главная</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-body-light" href="/urls">Сайты</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <?php if (is_array($messages)): ?>
      <?php foreach($messages as $key => $message): ?>
        <?php foreach($message as $item): ?>
          <?php if ($key === 'error'): ?>
            <div class="alert alert-danger" role="alert">
              <?= $item ?>
            </div>
          <?php elseif ($key === 'success'): ?>
            <div class="alert alert-success" role="alert">
              <?= $item ?>
            </div>
          <?php endif ?>
        <?php endforeach ?>
      <?php endforeach ?>
    <?php endif ?>

    <div class="card-body sticky-xl-top">
      <div class="text-start mb-2 container" style="width: 100vw">
        <h1>Сайт: <?= $name ?></h1>
        <table class="table table-bordered border-primary" data-test="url">
          <tr>
            <th>ID</th>
            <td><?= $id ?></td>
          </tr>
          <tr>
            <th>Имя</th>
            <td><?= $name ?></td>
          </tr>
          <tr>
            <th>Дата создания</th>
            <td><?= $timestamp ?></td>
          </tr>
        </table>
      </div>

      <div class="text-start mb-2 container" style="width: 100vw; margin-top: 4rem">
        <h1>Проверки</h1>
        <form action="/urls/<?= $id ?>/checks" method='post'>
          <input type='submit' class="btn btn-primary btn-sm" value='Запустить проверку'>
        </form>
        <table class="table table-bordered border-primary" data-test="checks">
          <thead>
            <tr>
              <th>ID</th>
              <th>Код ответа</th>
              <th>h1</th>
              <th>title</th>
              <th>Description</th>
              <th>Дата создания</th>
            </tr>
          </head>
          <tbody>
            <?php foreach ($checks as $check): ?>
              <tr>
                <td><?= $check['id'] ?></td>
                <td><?= $check['status'] ?></td>
                <td><?= $check['h1'] ?></td>
                <td><?= $check['title'] ?></td>
                <td><?= $check['description'] ?></td>
                <td><?= $check['timestamp'] ?></td>
              </tr>
            <?php endforeach ?>
          </tbody>
        </table>
      </div>
    </div>

    <div class="card-footer sticky-bottom text-center text-body-secondary">
      <a href="https://ru.hexlet.io/pages/about">Hexlet</a>
    </div>
  </dov>
</body>
