<head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
</head>
<body>
  <div class="card" style="height: 100vh">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand text-body-light" href="/">Анализатор страниц</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link text-body-light" aria-current="page" href="/">Главная</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-body-light" href="/urls">Сайты</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <?php if (is_array($messages)): ?>
      <?php //foreach($messages as $key => $message): ?>
        <?php //foreach($message as $item): ?>
          <?php if (array_key_exists('error', $messages)): //($key === 'error'): ?>
            <div class="alert alert-danger" role="alert">
              <?= array_last($messages['error'])//$item ?>
            </div>
          <?php elseif (array_key_exists('success', $messages))://($key === 'success'): ?>
            <div class="alert alert-success" role="alert">
              <?= array_last($messages['success'])//$item ?>
            </div>
          <?php endif ?>
        <?php //endforeach ?>
      <?php //endforeach ?>
    <?php endif ?>

    <div class="card-body sticky-xl-top">
      <div class="text-start mb-2 container" style="width: 100vw">
        <h1>Сайт: <?= $url->getUrl() ?></h1>
        <table class="table table-bordered border-primary" data-test="url">
          <tr>
            <td>ID</td>
            <td><?= $url->getId() ?></td>
          </tr>
          <tr>
            <td>Имя</td>
            <td><?= $url->getUrl() ?></td>
          </tr>
          <tr>
            <td>Дата создания</td>
            <td><?= $url->getTimestamp() ?></td>
          </tr>
        </table>
      </div>

      <div class="text-start mb-2 container" style="width: 100vw; margin-top: 4rem">
        <h1>Проверки</h1>
        <form action="/urls/<?= $url->getId() ?>/checks" method='post'>
          <input type='submit' class="btn btn-primary btn-sm" value='Запустить проверку'>
        </form>
        <table class="table table-bordered border-primary" data-test="checks">
          <tr>
            <td>ID</td>
            <td>Код ответа</td>
            <td>h1</td>
            <td>title</td>
            <td>Description</td>
            <td>Дата создания</td>
          </tr>
          <?php foreach ($checks as $check): ?>
            <tr>
              <td><?= $check->getId() ?></td>
              <td><?= $check->getStatus() ?></td>
              <td><?= $check->getH1() ?></td>
              <td><?= $check->getTitle() ?></td>
              <td><?= $check->getDescription() ?></td>
              <td><?= $check->getTimestamp() ?></td>
            </tr>
          <?php endforeach ?>
        </table>
      </div>
    </div>

    <div class="card-footer sticky-bottom text-center text-body-secondary">
      <a href="https://ru.hexlet.io/pages/about">Hexlet</a>
    </div>
  </dov>
</body>
