<head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
</head>
<body>
  <div class="card" style="height: 100vh">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand text-body-light" href="/">Анализатор страниц</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link text-body-light" aria-current="page" href="/">Главная</a>
            </li>
            <li class="nav-item">
              <a class="nav-link text-body-light" href="/urls">Сайты</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="card-body sticky-xl-top">
      <div class="text-start mb-2 container" style="width: 100vw">
        <h1>Сайты</h1>
        <table class="table table-bordered border-primary" data-test="urls">
          <tr>
            <td>ID</td>
            <td>Имя</td>
            <td>Последняя проверка</td>
            <td>Код ответа</td>
          </tr>
          <?php foreach ($urls as $url): ?>
            <tr>
              <?php $id =  $url->getId() ?>
              <td><?= $id ?></td>
              <td><a href="/urls/<?= $id ?>"><?= $url->getUrl() ?></a></td>
              <td>
                <?php if (count($urlChecks = $urlCheckRepo->getEntitiesByUrlId($id)) > 0): ?>
                  <?= $urlChecks[0]->getTimestamp() ?>
                <?php endif ?>
              </td>
              <td>
                <?php if (count($urlChecks) > 0): ?>
                  <?= $urlChecks[0]->getStatus() ?>
                <?php endif ?>
              </td>
            </tr>
          <?php endforeach ?>
        </table>
      </div>
    </div>

    <div class="card-footer sticky-bottom text-center text-body-secondary">
      <a href="https://ru.hexlet.io/pages/about">Hexlet</a>
    </div>
  </div>
</body>
