<head>
  <title>Список сайтов</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
</head>
<body>
  <div class="card" style="height: 100vh">
    <?php include __DIR__ . "/../navbar.phtml" ?>

    <?php if (is_array($messages)): ?>
      <?php foreach($messages as $key => $message): ?>
        <?php foreach($message as $item): ?>
          <?php if ($key === 'error'): ?>
            <div class="alert alert-danger" role="alert"">
              <?= htmlspecialchars($item ?: '', ENT_QUOTES) ?>
            </div>
          <?php elseif ($key === 'success'): ?>
            <div class="alert alert-success" role="alert"">
              <?= htmlspecialchars($item ?: '', ENT_QUOTES) ?>
            </div>
          <?php endif ?>
        <?php endforeach ?>
      <?php endforeach ?>
    <?php endif ?>

    <div class="card-body sticky-xl-top">
      <div class="text-start mb-2 container" style="width: 100vw">
        <h1>Сайты</h1>
        <table class="table table-bordered border-primary" data-test="urls">
          <thead>
            <tr>
              <th>ID</th>
              <th>Имя</th>
              <th>Последняя проверка</th>
              <th>Код ответа</th>
            </tr>
          </thead>
          <tbody>
            <?php foreach ($urls as $url): ?>
              <tr>
                <?php $id =  $url['id'] ?>
                <td><?= htmlspecialchars($id ?: '', ENT_QUOTES) ?></td>
                <td>
                  <a href="/urls/<?= htmlspecialchars($id ?: '', ENT_QUOTES) ?>"
                  title="Ссылка для перехода на страницу описания проверки URL">
                    <?= htmlspecialchars($url['name'] ?: '', ENT_QUOTES) ?>
                  </a>
                </td>
                <td><?= htmlspecialchars($url['timestamp'] ?: '', ENT_QUOTES) ?></td>
                <td><?= htmlspecialchars($url['status'] ?: '', ENT_QUOTES) ?></td>
              </tr>
            <?php endforeach ?>
          </tbody>
        </table>
      </div>
    </div>

    <div class="card-footer sticky-bottom text-center text-body-secondary">
      <a href="https://ru.hexlet.io/pages/about" title="Ссылка для перехода на страницу онлайн школы Хекслет">
        Hexlet
      </a>
    </div>
  </div>
</body>
