
<div class="text-start mb-2 container" style="width: 100vw">
  <h1>Сайты</h1>
  <table class="table table-bordered border-primary" data-test="urls">
    <thead>
      <tr>
        <th>ID</th>
        <th>Имя</th>
        <th>Последняя проверка</th>
        <th>Код ответа</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($urls as $url): ?>
        <tr>
          <?php $id = $url['id'] ?>
          <td><?= htmlspecialchars($id ?: '', ENT_QUOTES) ?></td>
          <td>
            <a href="<?= $router->urlFor('url.show', ['id' => htmlspecialchars($id ?: '', ENT_QUOTES)]) ?>"
            title="Ссылка для перехода на страницу описания проверки URL">
              <?= htmlspecialchars($url['name'] ?: '', ENT_QUOTES) ?>
            </a>
          </td>
          <td><?= htmlspecialchars($url['timestamp'] ?: '', ENT_QUOTES) ?></td>
          <td><?= htmlspecialchars($url['status'] ?: '', ENT_QUOTES) ?></td>
        </tr>
      <?php endforeach ?>
    </tbody>
  </table>
</div>
