<?php if (is_array($messages)): ?>
  <?php foreach($messages as $key => $message): ?>
    <?php foreach($message as $item): ?>
      <?php if ($key === 'error'): ?>
        <div class="alert alert-danger" role="alert">
          <?= htmlspecialchars($item ?: '', ENT_QUOTES) ?>
        </div>
        <?php elseif ($key === 'success'): ?>
        <div class="alert alert-success" role="alert">
          <?= htmlspecialchars($item ?: '', ENT_QUOTES) ?>
        </div>
      <?php endif ?>
    <?php endforeach ?>
  <?php endforeach ?>
<?php endif ?>
