
<div class="card text-start mb-3 container" style="width: 38rem; background: #f8f9fb">
  <div class="card-body">
    <h1 class="card-title">Анализатор страниц</h1>
    <p class="card-text">Бесплатно проверяйте сайты на SEO пригодность</p>
    <form action="/urls" method="post">
      <div class="input-group mb-3">
        <input type="text" class="form-control" name="url[name]"
        aria-label="Recipient’s username" aria-describedby="button-addon2"
        <?php if (!empty($errors) && isset($errors['url'])): ?>
          placeholder = <?= htmlspecialchars($errors['url']['name'] ?: '', ENT_QUOTES) ?>
        <?php else: ?>
          placeholder = "https://www.example.com"
        <?php endif ?>
        >
        <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Проверить</button>
      </div>
    </form>
  </div>
</div>
