<head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
</head>
<body>
  <div class="card" style="height: 100vh">
    <nav class="navbar p-3 mb-2 bg-dark text-white" style="--bs-breadcrumb-divider: '';" aria-label="breadcrumb">
      <div class="hstack gap-3">
        <h4 class="p-2">Анализатор страниц</h4>
        <ol class="breadcrumb">
          <li class="breadcrumb-item p-2"><a href="/main">Главная</a></li>
          <li class="breadcrumb-item p-2"><a href="/sites">Сайты</a></li>
        </ol>
      </div>
    </nav>

    <div class="card-body sticky-xl-top">
      <div class="card text-start mb-3 container" style="width: 38rem; background: #f8f9fb">
        <div class="card-body">
          <h1 class="card-title">Анализатор страниц</h1>
          <p class="card-text">Бесплатно проверяйте сайты на SEO пригодность</p>
          <form action="/check" method="post">
            <div class="input-group mb-3">
              <input type="text" class="form-control" placeholder="https://www.example.com" aria-label="Recipient’s username" aria-describedby="button-addon2">
              <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Проверить</button>
            </div>
          </form>
        </div>
      </div>
    </div>

    <div class="card-footer sticky-bottom text-center text-body-secondary">
      <a href="https://ru.hexlet.io/pages/about">Hexlet</a>
    </div>
  </div>
</body>