<head>
  <title><?= $title ?></title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
</head>
<body>
  <div class="card" style="height: 100vh">
    <?php require_once __DIR__ . "/navbar.phtml" ?>
    <?php require_once __DIR__ . "/alert.phtml" ?>

    <div class="card-body sticky-xl-top">
      <?= $content ?>
    </div>

    <div class="card-footer sticky-bottom text-center text-body-secondary">
      <a href="https://ru.hexlet.io/pages/about" title="Ссылка для перехода на страницу онлайн школы Хекслет">
        Hexlet
      </a>
    </div>
  </div>
</body>
