<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand text-body-light" href="<?= $router->urlFor('index') ?>">
      Анализатор страниц
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link text-body-light" aria-current="page" href="<?= $router->urlFor('index') ?>" title="Ссылка для перехода на главную страницу">
            Главная
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-body-light" href="<?= $router->urlFor('urls.show') ?>" title="Ссылка для перехода на страницу со списком URL">
            Сайты
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>
