name: check-for-linter
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    environment: sonar-qube-test

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup PHP with XDEBUG
        uses: shivammathur/setup-php@44454db4f0199b8b9685a5d763dc37cbf79108e1
        with:
          php-version: '8.5'
          coverage: xdebug

      - name: Install project and dependencies
        run: make install

      - name: Validate files for linter
        run: make lint
        
      - name: Run unit tests
        run: make test-sonar
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          DATABASE_URL: pgsql://postgres:password@localhost:5432/test

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
